test_is_numCoursincremented_correctly (__main__.EnrollInTestCase) ... ok
test_test (__main__.EnrollInTestCase) ... FAIL

======================================================================
FAIL: test_test (__main__.EnrollInTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "student_test.py", line 23, in test_test
    self.assertTrue(False)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (failures=1)
